config/routes.rb
Rails.application.routes.draw do
  get 'graph/index'
  root 'standard_format_data#index'
  
  resources :standard_format_data do
    collection do
      get 'import_csv_new'
      post 'import_csv'
    end
  end

end

app/models/standard_format_datum.rb
class StandardFormatDatum < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/graph_controller.rb
class GraphController < ApplicationController
  def index
    @reports = StandardFormatDatum.select("男女区分","身長","体重","総コレステロール").page(params[:page]).per(25).order(:"身長")
  	c1 = Array.new
  	c2 = Array.new
    c3 = Array.new
    c4 = Array.new

  	@reports.each do |c|
  		c1 << c.男女区分
  		c2 << c.身長
      c3 << c.体重
      c4 << c.総コレステロール
  	end 

    @graph = LazyHighCharts::HighChart.new('graph') do |f|
      f.title(text: '身長の推移')
      f.xAxis(categories: c1)
      f.series(name: '身長', data: c2, type: 'scatter')
    end

    @graph1 = LazyHighCharts::HighChart.new('graph1') do |f|
      f.title(text: '体重の推移')
      f.xAxis(categories: c1)
      f.series(name: '体重', data: c3, type: 'pie')
    end

    @graph2 = LazyHighCharts::HighChart.new('graph2') do |f|
      f.title(text: '総コレステロールの推移')
      f.xAxis(categories: c1)
      f.series(name: '総コレステロール', data: c4, type: 'column')
    end
  end
end

app/controllers/standard_format_data_controller.rb
class StandardFormatDataController < ApplicationController
  def index
    @count = StandardFormatDatum.count
    @reports = StandardFormatDatum.select("男女区分","生年月日","医療機関コード","身長","体重","総コレステロール").page(params[:page]).per(25).order(:"身長")
  end

  def import_csv_new  
  end

  def import_csv
	respond_to do |format|
	  if StandardFormatData.import_csv(params[:csv_file])
        format.html { redirect_to standard_format_data_path }
      else
        format.html { redirect_to standard_format_data_path, :notice => "CSVファイルの読み込みに失敗しました。" }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/graph_helper.rb
module GraphHelper
end

app/helpers/standard_format_data_helper.rb
module StandardFormatDataHelper

	def basho(value)
		if value == 14
			"石川県"
		elsif value == 24
			"西宮市"
		elsif value == 29
			"福岡市"
		elsif value == 30
			"佐賀県"
		elsif value == 44
			"同友会"
		elsif value == 54
			"臼杵市"
		elsif value == 55
			"生光会"
		elsif value == 67
			"宗像市"
		elsif value == 80
			"半田市"

		end
	end

	def danjo(value)
		if value == 1
			"男"
		elsif value == 2
			"女"
		end
	end

	def nenrei(value)
		return value if value.nil?

		today = Date.today
		age = today.year - value.year
		if today.month < value.month or (today.month == value.month and today.day < value.day)
			age -= 1
		else 
			age
		end
	end
end

app/views/graph/_graph.html.erb
<%= high_chart("sample", @graph) %>

app/views/graph/_graph1.html.erb
<%= high_chart("sample1", @graph1) %>

app/views/graph/index.html.erb
<%= high_chart("sample", @graph) %>
<%= high_chart("sample1", @graph1) %>
<%= high_chart("sample2", @graph2) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CsvImportGraph</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/standard_format_data/index.html.erb
<h1>検診結果一覧</h1>
</br>
<p>件数 <%= @count %>件</p>
</br>
<%= paginate @reports %>
<table class="table2">
  <thead>
    <tr>
      <th>場所</th>
      <th>男女区分</th>
      <th>生年月日</th>
      <th>年齢</th>>
      <th>身長</th>
      <th>体重</th>
      <th>総コレステロール</th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= basho(report.医療機関コード) %></td> 
        <td><%= danjo(report.男女区分) %></td>
        <td><%= report.生年月日 %></td>
        <td><%= nenrei(report.生年月日) %></td>
        <td><%= report.身長 %></td>
        <td><%= report.体重 %></td>
        <td><%= report.総コレステロール %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @reports %>
</br>
<%= form_tag({controller: "standard_format_data", action: "import_csv", method: "post"}, {multipart: true}) do %>
  <div class="field"> 
    <%= file_field_tag :csv_file %>
  </div>
  
  <div class="actions">
    <%= submit_tag "csvファイルを読み込む"%>
  </div>
<% end %>
</br>
<%= link_to 'グラフを表示', graph_index_path %>